name: fractal_base
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.2.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.3.0
  fractal:
    path: ../fractal
  signed_fractal:
    path: ../signed_fractal
  frac:
    path: ../frac
  path: ^1.8.3
  sqlite3_async: ^1.0.4
  sqlite3_web: ^0.1.0-wip
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
