name: fractal_base
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.4.5
  fractal:
    path: ../fractal
  signed_fractal:
    path: ../signed_fractal
  frac:
    path: ../frac
  path: ^1.8.3
  sqlite3_async: ^1.0.5
  sqlite3_web: ^0.1.2-wip
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
